Repository prgrms-fe-devcourse/NFE1-1-3-Calmiary, pull requests merged in 2024-10, with the labels that each got.

#1 [Feature] 폴더 세팅
  README.md
  eslint.config.js
  src/App.css
  src/App.tsx
  src/assets/close-x.svg
  src/assets/community-comment.svg
  src/assets/community-empty_heart.svg
  src/assets/community-filed_heart.svg
  src/assets/diary-left.svg
  src/assets/diary-right.svg
  src/assets/home-calendar.svg
  src/assets/home-history.svg
  src/assets/home-pen.svg
  src/assets/nav-community.svg
  src/assets/nav-home.svg
  src/assets/nav-log.svg
  src/assets/nav-profile.svg
  src/assets/nav-write.svg
  src/assets/react.svg
  src/assets/write-submit.svg
  src/components/ui/Icon.tsx
  src/features/community/CommunityPage.tsx
  src/features/community/hook/useFetchCommunity.tsx
  src/hook/AppCustomHookTest.tsx
  src/hook/useScreenSize.ts
  src/hook/useThottle.tsx
  src/index.css
  src/main.tsx
  src/network/axiosInstance/constants.js
  src/network/axiosInstance/index.ts
  src/network/react-query/constants.js
  src/network/react-query/key-factories.ts
  src/network/react-query/queryClient.ts
  src/styles/globalStyle.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  vite.config.ts
Labels: ⚙️ setting

#9 [Feature/#2] writing page 상호작용 없는 단순 UI 구현
  .github/ISSUE_TEMPLATE/description-tasks.md
  src/App.tsx
  src/assets/write-background.svg
  src/assets/write-emotion-angry.svg
  src/assets/write-emotion-cry.svg
  src/assets/write-emotion-scary.svg
  src/assets/write-emotion-smile.svg
  src/assets/write-emotion-soso.svg
  src/components/ui/Icon.tsx
  src/features/writing/WritingPage.tsx
  src/features/writing/components/ContentInput.tsx
  src/features/writing/components/ContentPublicButton.tsx
  src/features/writing/components/EmotionInput.tsx
  src/features/writing/components/MoveToMainButton.tsx
  src/features/writing/components/QuestionBox.tsx
  src/features/writing/components/ResponseBox.tsx
  src/features/writing/components/index.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ✨ feature

#10 [Feature/#4] 데이터베이스 스키마 및 앤드포인트 구현
  backend/database.py
  backend/main.py
  backend/model/models.py
  backend/model/schemas.py
  backend/static/index.html
  backend/table/__init__.py
  backend/table/data.py
  backend/templates/admin.html
  backend/templates/table.html
Labels: ✨ feature

#18 [Feature/#13] 다이어리 관련 API 구현
  backend/main.py
  backend/routes/auth.py
  backend/routes/diary.py
  backend/routes/stats.py
  backend/utils/security.py
  backend/utils/token_manager.py
Labels: ✨ feature

#20 [Feature/#7] community page UI 구현
  src/App.tsx
  src/assets/comuunity-dropdown.svg
  src/features/community/CommunityPage.tsx
  src/features/community/components/DropDown.tsx
  src/features/community/components/Post.tsx
  src/features/community/components/PostContent.tsx
  src/features/community/components/PostReaction.tsx
  src/features/community/components/Title.tsx
  src/features/community/components/UserInfo.tsx
  src/features/community/components/index.ts
  src/features/community/components/mockData.ts
Labels: ✨ feature, 🎨 design

#14 [Feature#6]프로필페이지 UI구현
  src/App.tsx
  src/components/ui/Icon.tsx
  src/features/profile/ProfilePage.tsx
  src/features/profile/components/ProfileButton.tsx
  src/features/profile/components/ProfileModal.tsx
  src/features/profile/pages/ProfileLikePage.tsx
  src/features/profile/pages/ProfileMainPage.tsx
  src/features/profile/pages/ProfileSharePage.tsx
  src/features/profile/pages/ProfileUserPage.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ✨ feature, 🎨 design

#21 [Feature/#19] 커뮤니티 관련 API 구현
  backend/main.py
  backend/routes/community.py
Labels: ✨ feature

#16 [Feature/#5] 다이어리 MainPage UI 구현
  src/assets/Emoji-angry.svg
  src/assets/Emoji-petulance.svg
  src/assets/Emoji-sad.svg
  src/assets/Emoji-smail.svg
  src/assets/Emoji-soso.svg
  src/assets/diary-info.svg
  src/components/ui/Icon.tsx
  src/features/diary/DiaryPage.tsx
  src/features/diary/components/DiaryEmoji.tsx
  src/features/diary/components/DiaryFilter.tsx
  src/features/diary/components/DiaryHeader.tsx
  src/features/diary/components/DiaryMonth.tsx
  src/features/diary/components/index.ts
  src/features/diary/pages/DiaryDetailPage.tsx
  src/features/diary/pages/DiaryMainPage.tsx
  src/features/diary/pages/index.ts
Labels: ✨ feature

#23 [Feature/#22] detail community page
  src/App.tsx
  src/assets/comment-update.svg
  src/features/community/components/PostReaction.tsx
  src/features/community/components/mockData.ts
  src/features/detailCommunity/DetailCommunityPage.tsx
  src/features/detailCommunity/components/CommentInput.tsx
  src/features/detailCommunity/components/Comments.tsx
  src/features/detailCommunity/components/CommentsContent.tsx
  src/features/detailCommunity/components/DetailPostContent.tsx
  src/features/detailCommunity/components/WorryContent.tsx
  src/features/detailCommunity/components/index.ts
Labels: ✨ feature, 🎨 design

#24 [Feature/#11] Writing Page 사용자와 상호작용 존재하는 UI 구현
  package-lock.json
  package.json
  src/features/writing/WritingPage.tsx
  src/features/writing/components/ContentInput.tsx
  src/features/writing/components/EmotionIcon.tsx
  src/features/writing/components/EmotionInput.tsx
  src/features/writing/components/EntireInput.tsx
  src/features/writing/components/LoadingSpinner.tsx
  src/features/writing/components/QuestionBox.tsx
  src/features/writing/components/ResponseBox.tsx
  src/features/writing/components/index.ts
  src/features/writing/hooks/useChangeMode.ts
  src/features/writing/types/formTypes.ts
  src/stores/writingModeStore.ts
  src/stores/writingResponseStore.ts
Labels: ✨ feature, 🎨 design

#32 [Feature/#17] 다이어리 MainPage UI 구현
  src/assets/imgs/diary-speech.png
  src/features/diary/DiaryPage.tsx
  src/features/diary/components/DiaryCalminaryAnswer.tsx
  src/features/diary/components/DiaryDetailEmojiAndDate.tsx
  src/features/diary/components/DiaryHeader.tsx
  src/features/diary/components/DiaryInfoToolTip.tsx
  src/features/diary/components/DiaryMyWorry.tsx
  src/features/diary/components/index.ts
  src/features/diary/pages/DiaryDetailPage.tsx
Labels: ✨ feature, 🎨 design

#30 [Feature/#29] 백엔드 코드 리팩토링 및 편의성 작업 추가
  backend/database.py
  backend/main.py
  backend/model/models.py
  backend/model/schemas.py
  backend/routes/admin.py
  backend/routes/auth.py
  backend/routes/community.py
  backend/routes/diary.py
  backend/routes/profile.py
  backend/routes/stats.py
  backend/table/__init__.py
  backend/table/data.py
  backend/templates/admin.html
  backend/templates/table.html
  backend/utils/date.py
Labels: ♻️ refactor

#35 [Feat] API 연결 및 CORS 문제 해결
  src/features/profile/pages/ProfileLikePage.tsx
  src/features/writing/components/EntireInput.tsx
  vite.config.ts
Labels: ✨ feature

#37 [Feature/#34] 프로필 이미지 업로드 및 URL 반환 기능 구현
  backend/main.py
  backend/routes/admin.py
  backend/routes/community.py
  backend/routes/profile.py
Labels: ✨ feature

#38 [Feature/#15] 좋아요 포스트, 공유한 포스트 UI
  src/App.tsx
  src/features/profile/components/Dropdown.tsx
  src/features/profile/components/LikePost.tsx
  src/features/profile/components/SharePost.tsx
  src/features/profile/pages/ProfileLikePage.tsx
  src/features/profile/pages/ProfileMainPage.tsx
  src/features/profile/pages/ProfileSharePage.tsx
  src/features/profile/pages/ProfileUserPage.tsx
Labels: ✨ feature, 🎨 design

#45 [Feature/#44] 홈 API 연결 및 수정
  backend/main.py
  src/features/home/api/stats.ts
  src/features/home/auth.ts
  src/features/home/components/HomeLayout.tsx
  src/features/home/components/HomeLogo.tsx
  src/features/home/components/LoginForm.tsx
  src/features/home/components/SignUpForm.tsx
  src/features/home/hooks/useAuth.ts
  src/features/home/hooks/useStats.ts
  src/features/home/hooks/useUser.ts
  src/features/home/pages/GrothPage.tsx
  src/features/home/pages/LoginPage.tsx
  src/features/home/pages/SignUpPage.tsx
  src/features/home/types/homeTypes.ts
  src/network/axiosInstance/constants.ts
Labels: ✨ feature

#49 [Feature/#26] community page api 연결
  src/App.tsx
  src/features/community/CommunityPage.tsx
  src/features/community/components/CommentInput.tsx
  src/features/community/components/Comments.tsx
  src/features/community/components/CommentsContent.tsx
  src/features/community/components/DetailPostContent.tsx
  src/features/community/components/DropDown.tsx
  src/features/community/components/Post.tsx
  src/features/community/components/PostContent.tsx
  src/features/community/components/PostReaction.tsx
  src/features/community/components/UserInfo.tsx
  src/features/community/components/WorryContent.tsx
  src/features/community/components/index.ts
  src/features/community/hook/useFetchCommunity.tsx
  src/features/community/pages/DetailCommunityPage.tsx
  src/features/community/types/community.ts
  src/features/community/types/index.ts
  src/features/detailCommunity/components/index.ts
Labels: ✨ feature

#53 [Feature/#47] 글쓰기 페이지 다른 페이지로 이동 구현
  package-lock.json
  package.json
  src/features/writing/WritingPage.tsx
  src/features/writing/components/EntireInput.tsx
  src/features/writing/components/Modal.tsx
  src/features/writing/components/MoveToMainButton.tsx
  src/features/writing/components/RetryButton.tsx
  src/features/writing/components/index.ts
  src/features/writing/hooks/useChangeMode.ts
  src/features/writing/hooks/useScrollFollow.ts
  src/stores/writingModeStore.ts
Labels: ✨ feature
