Repository prgrms-fe-devcourse/NFE1-1-3-Calmiary, pull requests merged in 2024-11, with the labels that each got.

#60 [Feature/#55] 프로필 유저정보수정 api연결
  src/features/profile/hook/useUpdateImageMutation.ts
  src/features/profile/hook/useUpdateUserMutation.ts
  src/features/profile/hook/useUserData.ts
  src/features/profile/pages/ProfileMainPage.tsx
  src/features/profile/pages/ProfileUserPage.tsx
  src/features/profile/types/profileTypes.ts
Labels: ✨ feature, 🎨 design

#57 [Feature/#50] detail community api
  src/App.tsx
  src/assets/default_profile_image.svg
  src/features/community/CommunityPage.tsx
  src/features/community/components/CommentInput.tsx
  src/features/community/components/Comments.tsx
  src/features/community/components/CommentsContent.tsx
  src/features/community/components/DetailPostContent.tsx
  src/features/community/components/Post.tsx
  src/features/community/components/UserInfo.tsx
  src/features/community/components/WorryContent.tsx
  src/features/community/components/mockData.ts
  src/features/community/pages/DetailCommunityPage.tsx
  src/features/community/types/community.ts
  src/features/community/types/detailCommunity.ts
  src/features/community/types/index.ts
Labels: ✨ feature

#62 [Feature/#56, #59] Toast 및 Navigation bar 구현
  src/App.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/Toast.tsx
  src/features/writing/WritingPage.tsx
  src/features/writing/components/Button.tsx
  src/features/writing/components/ContentInput.tsx
  src/features/writing/components/ContentPublicButton.tsx
  src/features/writing/components/EmotionInput.tsx
  src/features/writing/components/EntireInput.tsx
  src/features/writing/components/Modal.tsx
  src/features/writing/components/MoveToMainButton.tsx
  src/features/writing/components/RetryButton.tsx
  src/features/writing/hooks/useMoveForm.ts
  src/features/writing/hooks/useMoveMutation.ts
  src/features/writing/hooks/useWriteForm.ts
  src/features/writing/hooks/useWriteMutation.ts
  src/features/writing/types/formTypes.ts
  src/features/writing/types/toastTypes.ts
  src/features/writing/utils/showToast.ts
  src/stores/toastStore.ts
  src/stores/writingModeStore.ts
  src/stores/writingResponseStore.ts
Labels: ✨ feature, 🎨 design

#66 [Feature/#61] 회원탈퇴 및 로그아웃 기능구현
  src/features/home/hooks/useUser.ts
  src/features/profile/components/ProfileModal.tsx
  src/features/profile/hook/useWithdrawMutation.ts
  src/features/profile/pages/ProfileLikePage.tsx
  src/features/profile/pages/ProfileMainPage.tsx
  src/features/profile/pages/ProfileSharePage.tsx
Labels: ✨ feature, 🎨 design

#63 [Feature/#52, #58] 다이어리 UI 구현 및 API 연결
  backend/main.py
  backend/model/schemas.py
  backend/routes/community.py
  backend/routes/diary.py
  src/App.tsx
  src/assets/info.svg
  src/assets/solve.svg
  src/features/diary/DiaryPage.tsx
  src/features/diary/api/diary.ts
  src/features/diary/components/DiaryCalminaryAnswer.tsx
  src/features/diary/components/DiaryDetailEmojiAndDate.tsx
  src/features/diary/components/DiaryEmoji.tsx
  src/features/diary/components/DiaryFilter.tsx
  src/features/diary/components/DiaryInfoToolTip.tsx
  src/features/diary/components/DiaryMonth.tsx
  src/features/diary/components/DiaryMyWorry.tsx
  src/features/diary/components/DiaryTitle.tsx
  src/features/diary/components/Switch.tsx
  src/features/diary/pages/DiaryDetailPage.tsx
  src/features/diary/pages/DiaryMainPage.tsx
  src/features/diary/pages/index.ts
  src/features/diary/types/diaryTypes.ts
Labels: ✨ feature

#65 [Feature/#64] 랜딩페이지 UI 구현
  src/App.tsx
  src/features/landing/pages/LandingPage.tsx
Labels: ✨ feature, 🎨 design

#67 [Feature/#64] 오류 수정 및 모달 추가
  backend/routes/diary.py
  package.json
  src/components/ErrorModal.tsx
  src/features/home/components/HomeLayout.tsx
  src/features/home/components/LoginForm.tsx
  src/features/home/hooks/useAuth.ts
  src/features/home/pages/LoginPage.tsx
  src/features/home/pages/SignUpPage.tsx
  src/features/landing/pages/LandingPage.tsx
Labels: ✨ feature, 🪚 fix

#71 [Feature/#70] detail community UI
  src/components/Skeleton.tsx
  src/features/community/components/CommentInput.tsx
  src/features/community/components/Comments.tsx
  src/features/community/components/CommentsContent.tsx
  src/features/community/components/DetailPostContent.tsx
  src/features/community/components/WorryContent.tsx
  src/features/community/pages/DetailCommunityPage.tsx
  src/features/community/types/detailCommunity.ts
  src/styles/skeletonStyle.ts
  tsconfig.app.tsbuildinfo
Labels: ✨ feature, 🎨 design

#73 [Feature/#68] Writing Page CORS 문제 + CSS 문제 해결
  src/App.tsx
  src/features/writing/WritingPage.tsx
  src/features/writing/components/MoveToMainButton.tsx
  src/features/writing/components/QuestionBox.tsx
  src/features/writing/hooks/useMoveMutation.ts
Labels: 🪚 fix

#77 [Feature/#74] 좋아요 토글시 오류 수정
  src/features/community/components/CommentsContent.tsx
  src/features/community/components/DetailPostContent.tsx
  src/features/community/components/WorryContent.tsx
  src/features/community/pages/DetailCommunityPage.tsx
Labels: 🪚 fix

#76 [Feature/#69] 프로필페이지 전체적인 수정
  src/features/profile/components/Modal.tsx
  src/features/profile/components/ProfilePost.tsx
  src/features/profile/pages/ProfileLikePage.tsx
  src/features/profile/pages/ProfileMainPage.tsx
  src/features/profile/pages/ProfileSharePage.tsx
  src/features/profile/pages/ProfileUserPage.tsx
  src/features/profile/types/profileTypes.ts
Labels: ✨ feature, 🪚 fix
